port: 4222

# TLS Config
tls {
  cert_file: "/etc/nats/certs/server.crt"
  key_file:  "/etc/nats/certs/server.key"
}

authorization {
  users = [
    # Box broker-client user
    { nkey: "UCHEF3IS3HS5SXBJBERQTRIPZ3QE64GSDBJPXDPH5Z2BSGRJXETGSWP2" }
    # broker setup user
    { nkey: "UAR2MLRAOYKVYHQP3HPK2KP5FGLTTRJ2PBNEGJYE5B35KJNWFYSSHPNW" }
    # Cleaner user
    { nkey: "UAK33VWVZN3LVCTAKV26RLF7L5NZ7ZBUVOAADH5A2BMID26PDYVCFMRG" }
    # Normalizer user
    { nkey: "UDP4RZVOYEUYFWZZAFUWUI746EPN6EGZUJYRWER5B5P6HIVGMYKA3ES4" }
    # Splitter user
    { nkey: "UAQREJZIZODIMIVX7OR2EHDVESWBBCSVTVSQHSSBKO5WHIJ76KVQIPO7" }
  ]
}

