services:
  nats:
    image: nats:latest
    hostname: nats-broker
    container_name: nats-broker-${STATION_NUMBER}
    command: ["-js","-sd", "/data"]
    volumes:
      - nats-data:/data
    # ports:
    #   - "${NATS_EXTERNAL_PORT}:4222"
    networks:
      - station-network

  setup-broker:
    image: ial/setup-stream
    container_name: setup-stream-${STATION_NUMBER}
    command: ["node", "dist/main.js"]
    depends_on:
      - nats
    environment:
      - NATS_SERVER=${NATS_SERVER}
    networks:
      - station-network
networks:
  station-network:
    name: ${STATION_NETWORK}
    driver: bridge
volumes:
  nats-data:
