sonar.organization=antoine-fdrg
sonar.projectKey=projet-IAL_setup-stream
sonar.projectName=setup-stream
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=node_modules/**
