services:
  cleaner:
    image: ial/cleaner
    container_name: cleaner
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - NATS_CONSUME_QUEUE=MEASUREMENT.to_clean
      - NATS_PUBLISH_QUEUE=MEASUREMENT.to_normalize
    networks:
      - nats-network
networks:
  nats-network:
    driver: bridge
