services:
  cleaner:
    image: ial/cleaner
    container_name: cleaner-prod
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - NATS_CONSUME_QUEUE=MEASUREMENT.to_clean
      - NATS_PUBLISH_QUEUE=MEASUREMENT.to_normalize
      - NATS_CA_FILE=${NATS_CA_FILE}
    volumes:
      - ./configuration/certs:/app/configuration/certs:ro
    networks:
      - nats-network-prod
networks:
  nats-network-prod:
    driver: bridge
