services:
  gatt-server:
      image: ial/gatt-server
      container_name: gatt-server
      restart: always
      env_file:
        - ../../box/gatt-server/.env
      ports:
        - "3000:3000"
      networks:
      - nats-network

  mock-watch:
      image: ial/mock-watch
      container_name: mock-watch
      restart: always
      env_file:
        - .env  
      tty: true
      networks:
      - nats-network

networks:
  nats-network:
    driver: bridge