services:
  mock-watch:
    image: ial/mock-watch
    container_name: mock-watch-${STATION_NUMBER}
    restart: always
    environment:
      - ENDPOINT_URL=${ENDPOINT_URL}
      - PULSE_INTERVAL_MS=${PULSE_INTERVAL_MS}
      - SEND_INTERVAL_MS=${SEND_INTERVAL_MS}
      - INIT_WEIGHT_KG=${INIT_WEIGHT_KG}
      - SOURCE_ID=${SOURCE_ID}
      - DEVICE_TYPE=${DEVICE_TYPE}
    tty: true
    networks:
      - home-network

networks:
  home-network:
    external: true
    name: ${HOME_NETWORK}
    driver: bridge
