services:
  splitter:
    image: ial/splitter
    container_name: splitter-prod
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - SPLITTER_CONSUME_QUEUE=MEASUREMENT.to_split
      - SPLITTER_PRODUCER_QUEUE=${SPLITTER_PRODUCER_QUEUE}
      - NATS_CA_FILE=${NATS_CA_FILE}
      - NATS_SEED=${NKEY_SEED_SPLITTER}
    volumes:
      - ./configuration/certs:/app/configuration/certs:ro
    networks:
      - nats-network-prod
networks:
  nats-network-prod:
    driver: bridge
