services:
  splitter:
    image: ial/splitter
    container_name: splitter
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    env_file: ".env.docker"
    networks:
      - nats-network
networks:
  nats-network:
    driver: bridge
