port: 4222

# TLS Config
tls {
  cert_file: "/etc/nats/certs/server.crt"
  key_file:  "/etc/nats/certs/server.key"
}

authorization {
  users = [
    # broker setup user
    { nkey: "UBLZY6A7TNE3WYSD5YDSD2YNTSKK6GAI4Y7JAT6I3KT3G4UOHKGNHTVY" }
    # Cleaner user
    { nkey: "UABP3K5WTYA6ISXA72RKSLME6E7SDVAC2CLPCBSINNCSHTN345G2DWIF" }
    # Box broker-client user
    { nkey: "UCHEF3IS3HS5SXBJBERQTRIPZ3QE64GSDBJPXDPH5Z2BSGRJXETGSWP2" }
  ]
}

