services:
  cleaner:
    image: ial/normalizer
    container_name: normalizer-prod
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - NORMALIZER_CONSUME_QUEUE=MEASUREMENT.to_normalize
      - NORMALIZER_PRODUCER_QUEUE=${NORMALIZER_PRODUCER_QUEUE}
      - NATS_CA_FILE=${NATS_CA_FILE}
      - NATS_SEED=${NKEY_SEED_CLEANER}
    volumes:
      - ./configuration/certs:/app/configuration/certs:ro
    networks:
      - nats-network-prod
networks:
  nats-network-prod:
    driver: bridge
