services:
  nats:
    image: nats:latest
    hostname: nats-broker
    container_name: nats-broker
    ports:
      - 4222:4222
    command: ["-js"]
    networks:
      - nats-network

  setup-broker:
    image: ial/broker-setup-broker
    container_name: setup-broker
    command: ["node", "dist/main.js"]
    depends_on:
      - nats
    environment:
      - NATS_SERVER=${NATS_SERVER}
    networks:
      - nats-network
networks:
  nats-network:
    driver: bridge
