services:
  box-broker-client:
    image: ial/box-broker-client
    container_name: box-broker-client
    depends_on:
      - setup-broker
    env_file: ".env.docker"
    networks:
      - nats-network
networks:
  nats-network:
    driver: bridge
