services:
  box-broker-client:
    image: ial/box-broker-client
    container_name: box-broker-client-prod
    depends_on:
      - setup-broker
    env_file: ".env.production"
    volumes:
      - ./configuration/certs:/app/configuration/certs:ro
    networks:
      - nats-network-prod
networks:
  nats-network-prod:
    driver: bridge
