services:
  cleaner:
    image: ial/cleaner
    container_name: cleaner-${STATION_NUMBER}
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - CLEANER_CONSUME_QUEUE=MEASUREMENT.to_clean
      - CLEANER_PRODUCER_QUEUE=${CLEANER_PRODUCER_QUEUE}
    networks:
      - station-network
networks:
  station-network:
    name: ${STATION_NETWORK}
    driver: bridge
