services:
  normalizer:
    image: ial/normalizer
    container_name: normalizer-${STATION_NUMBER}
    command: ["node", "dist/main.js"]
    depends_on:
      - setup-broker
    environment:
      - NATS_SERVER=${NATS_SERVER}
      - NORMALIZER_CONSUME_QUEUE=MEASUREMENT.to_normalize
      - NORMALIZER_PRODUCER_QUEUE=${NORMALIZER_PRODUCER_QUEUE}
    networks:
      - station-network
networks:
  station-network:
    name: ${STATION_NETWORK}
    driver: bridge