sonar.projectKey=save-service
sonar.organization=antoine-fdrg
sonar.projectName=save-service
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**

